{
 "title": "CPU监控",
 "description": "CPU详细监控",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "主机名",
    "query": "label_values(node_load1, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU总核数",
   "type": "singlestat",
   "description": "逻辑CPU总个数",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"})"
    }
   ]
  },
  {
   "title": "CPU总利用率",
   "type": "graph",
   "description": "CPU总利用率",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(1 - avg by (instance) (irate(node_cpu_seconds_total{instance=~\"$node\", mode=\"idle\"}[5m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU user",
   "type": "graph",
   "description": "用户空间CPU利用率",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (irate(node_cpu_seconds_total{instance=~\"$node\", mode=\"user\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU system",
   "type": "graph",
   "description": "system空间CPU利用率",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (irate(node_cpu_seconds_total{instance=~\"$node\", mode=\"user\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "graph",
   "description": "iowait CPU利用率",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (irate(node_cpu_seconds_total{instance=~\"$node\", mode=\"iowait\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU steal",
   "type": "graph",
   "description": "steal CPU利用率",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (irate(node_cpu_seconds_total{instance=~\"$node\", mode=\"steal\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU softirq",
   "type": "graph",
   "description": "softirq CPU利用率",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (irate(node_cpu_seconds_total{instance=~\"$node\", mode=\"softirq\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU irq",
   "type": "graph",
   "description": "irq CPU利用率",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (irate(node_cpu_seconds_total{instance=~\"$node\", mode=\"irq\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}