{
 "title": "服务器配置信息(静态)",
 "description": "服务器基本配置信息，比如cpu cores数量，内存大小，启动时间等",
 "tags": [
  "服务器",
  "server",
  "basic",
  "config"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "主机名",
    "query": "label_values(node_boot_time_seconds, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU总核数",
   "type": "singlestat",
   "description": "逻辑CPU总个数",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"})"
    }
   ]
  },
  {
   "title": "内存大小",
   "type": "singlestat",
   "description": "物理内存大小",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes {instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "SWAP大小",
   "type": "singlestat",
   "description": "SWAP空间大小",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes  {instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "RootFS大小",
   "type": "singlestat",
   "description": "RootFS（根分区）大小",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=\"rootfs\",fstype=\"rootfs\",mountpoint=\"/\",instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "启动时间",
   "type": "singlestat",
   "description": "物理内存大小",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "format": "s",
   "valueName": "min",
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$node\"} - node_boot_time_seconds{instance=~\"$node\"}"
    }
   ]
  }
 ]
}