{
 "title": "服务器磁盘信息",
 "description": "服务器基本信息监控，通过相关的链接可以查看某个相关指标的详情",
 "tags": [
  "服务器",
  "server",
  "disk",
  "磁盘"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "主机名",
    "query": "label_values(node_boot_time_seconds, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "硬盘使用率",
   "type": "graph",
   "description": "表示硬盘的使用率，反映磁盘的繁忙程度；注意，不是硬盘空间的使用率",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~'$node', device!~'^(sr|nbd|dm).*$'}[5m])",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "延时",
   "type": "graph",
   "description": "i/o操作延时(await time)表示某个时间段内每个io所花费的平均时间",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "1000 * (increase(node_disk_read_time_seconds_total{instance=~\"$node\", device!~'^(sr|nbd|dm).*$'}[30s])/(increase(node_disk_reads_completed_total{instance=~\"$node\", device!~'^(sr|nbd|dm).*$'}[30s])+0.00000001)) + 1000 * (increase(node_disk_write_time_seconds_total{instance=~\"$node\", device!~'^(sr|nbd|dm).*$'}[30s])/(increase(node_disk_writes_completed_total{instance=~\"$node\", device!~'^(sr|nbd|dm).*$'}[30s])+0.00000001))",
     "legendFormat": "{{instance}}-{{device}}-总延时"
    },
    {
     "expr": "1000 * (increase(node_disk_read_time_seconds_total{instance=~\"$node\", device!~'^(sr|nbd|dm).*$'}[30s])/(increase(node_disk_reads_completed_total{instance=~\"$node\", device!~'^(sr|nbd|dm).*$'}[30s])+0.00000001))",
     "legendFormat": "{{instance}}-{{device}}-读延时"
    },
    {
     "expr": "1000 * (increase(node_disk_write_time_seconds_total{instance=~\"$node\", device!~'^(sr|nbd|dm).*$'}[30s])/(increase(node_disk_writes_completed_total{instance=~\"$node\", device!~'^(sr|nbd|dm).*$'}[30s])+0.00000001))",
     "legendFormat": "{{instance}}-{{device}}-写延时"
    }
   ]
  },
  {
   "title": "写IOPS",
   "type": "graph",
   "description": "写磁盘的IOPS，表示平均每秒钟写操作的次数",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~'$node', device!~'^(sr|nbd|dm).*$'}[5m])",
     "legendFormat": "{{instance}}_{{device}}"
    }
   ]
  },
  {
   "title": "读IOPS",
   "type": "graph",
   "description": "读磁盘的IOPS，表示平均每秒钟读操作的次数",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~'$node', device!~'^(sr|nbd|dm).*$'}[5m])",
     "legendFormat": "{{instance}}_{{device}}"
    }
   ]
  },
  {
   "title": "写速率",
   "type": "graph",
   "description": "写磁盘的速率，表示平均每秒钟写入的数据量",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~'$node', device!~'^(sr|nbd|dm).*$'}[5m])",
     "legendFormat": "{{instance}}_{{device}}"
    }
   ]
  },
  {
   "title": "读速率",
   "type": "graph",
   "description": "读磁盘的速率，表示平均每秒钟读取的数据量",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~'$node', device!~'^(sr|nbd|dm).*$'}[5m])",
     "legendFormat": "{{instance}}_{{device}}"
    }
   ]
  },
  {
   "title": "写操作平均大小",
   "type": "graph",
   "description": "每次写操作平均写入的数据量",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(node_disk_written_bytes_total{instance=~'$node', device!~'^(sr|nbd|dm).*$'}[30s]) / (increase(node_disk_writes_completed_total{instance=~'$node', device!~'^(sr|nbd|dm).*$'}[30s]) + 0.000000001)",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "读操作平均大小",
   "type": "graph",
   "description": "每次读操作平均读取的数据量",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(node_disk_read_bytes_total{instance=~'$node', device!~'^(sr|nbd|dm).*$'}[30s]) / (increase(node_disk_reads_completed_total{instance=~'$node', device!~'^(sr|nbd|dm).*$'}[30s]) + 0.000000001)",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "写操作合并速率",
   "type": "graph",
   "description": "写操作合并速率",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_writes_merged_total{instance=~'$node', device!~'^(sr|nbd|dm).*$'}[5m])",
     "legendFormat": "{{instance}}_{{device}}"
    }
   ]
  },
  {
   "title": "读操作合并速率",
   "type": "graph",
   "description": "读操作合并速率",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_writes_merged_total{instance=~'$node', device!~'^(sr|nbd|dm).*$'}[5m])",
     "legendFormat": "{{instance}}_{{device}}"
    }
   ]
  }
 ]
}