{
 "title": "服务器基本信息",
 "description": "服务器基本信息监控，通过相关的链接可以查看某个相关指标的详情",
 "tags": [
  "服务器",
  "server",
  "basic",
  "基础指标"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "主机名",
    "query": "label_values(node_load1, instance)"
   },
   {
    "name": "interface",
    "label": "网卡名",
    "query": "label_values(node_network_receive_bytes_total, device)"
   }
  ]
 },
 "panels": [
  { "title": "负载", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "系统负载",
   "type": "graph",
   "description": "系统负载，包括load1, load5和load15三个指标",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_load1"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_load5"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_load15"
    }
   ]
  },
  {
   "title": "CPU总利用率",
   "type": "graph",
   "description": "所有CPU Core的总利用率",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(1 - avg by (instance) (irate(node_cpu_seconds_total{instance=~\"$node\", mode=\"idle\"}[5m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "内存", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "内存使用率",
   "type": "graph",
   "description": "内存使用率，在3.10内核中可用内存字段为node_memory_MemAvailable_bytes，在2.6内核中可用内存字段为node_memory_MemFree_bytes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} or node_memory_MemFree_bytes{instance=~\"$node\"})/node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Swap使用率",
   "type": "graph",
   "description": "内存交换空间使用率。\n分母加上0.000000001是为了避免交换空间为0时，在grafana数据展示为空的问题；如果设置为null为zero，在监控agent部署之前，所有的数据都为0是不准确的。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$node\"} - node_memory_SwapFree_bytes{instance=~\"$node\"}) / (node_memory_SwapTotal_bytes{instance=~\"$node\"} + 0.000000001)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "网卡流量", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "网卡流量-IN",
   "type": "graph",
   "description": "进入网卡的流量值",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node', device!~'(\\\\?=brq|docker|dummy|lo|tap|tun|veth|kube|\\\\w+\\\\.\\\\w).*$'}[5m])",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "网卡流量-OUT",
   "type": "graph",
   "description": "从网卡出去的流量值",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node', device!~'(\\\\?=brq|docker|dummy|lo|tap|tun|veth|kube|\\\\w+\\\\.\\\\w).*$'}[5m])",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  },
  { "title": "文件系统", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "文件系统空间使用率",
   "type": "graph",
   "description": "文件系统的存储空间使用率",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_filesystem_avail_bytes{instance=~\"$node\", fstype!=\"tmpfs\", device!=\"rootfs\"}/node_filesystem_size_bytes{instance=~\"$node\", fstype!=\"tmpfs\", device!=\"rootfs\"}",
     "legendFormat": "{{instance}}-{{mountpoint}}"
    }
   ]
  },
  {
   "title": "文件系统inode使用率",
   "type": "graph",
   "description": "文件系统的inode使用率",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_filesystem_files_free{instance=~\"$node\", fstype!=\"tmpfs\", device!=\"rootfs\"}/node_filesystem_files{instance=~\"$node\", fstype!=\"tmpfs\", device!=\"rootfs\"}",
     "legendFormat": "{{instance}}-{{mountpoint}}"
    }
   ]
  },
  { "title": "硬盘利用率+TCP连接数", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "硬盘Util",
   "type": "graph",
   "description": "表示硬盘的使用率，反映磁盘的繁忙程度；注意，不是硬盘空间的使用率",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~'$node', device!~'^(sr|nbd|dm).*$'}[5m])",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "TCP连接数",
   "type": "graph",
   "description": "TCP连接数",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}